Fix compile errors caused by "#define MNN_THREAD_LOCK_CPU"
error: sort is not a member of std
error: gettid was not declared in this scope
error: __NR_sched_setaffinity was not declared in this scope
error: syscall was not declared in this scope